name: scope
channels: [pytorch, conda-forge]
dependencies:
  - python=3.10
  - pytorch
  - numpy
  - pyyaml
  - pandas
  - matplotlib
  - pytest
  - scikit-learn
  - h5py
  - pip
  - pip:
      - webdataset
